#! /bin/bash
### BEGIN INIT INFO
# Provider: wang
# Required-Start: $remote_fs
# Required-Stop: $remote_fs
# Default-Start:2 3 4 5
# Default-Stop:0 1 6
# Short-Description:Remote control pi car
# Description:This service is used to start or stop Pi car programs
### END INIT INFO
case "$1" in
    "start"):
      ech0 "Starting PiCarService"
      cd /home/pi/Desktop/Patrol-Robot/mjpg-streamer-pplite_v2.8/mjpg-streamer-experimental/
      sh start.sh &
      python3 /home/pi/Desktop/Patrol-Robot/RasPiCar_V1.5/raspicar.py &
      ;;
    "stop"):
      ech0 "Stopping PiCarService"
      sudo killall start.sh
      sudo killall raspicar.py
      sudo killall PiCarService
      ;;
    *)
      echo "Usage:service PiCarService start|stop"
      exit 1
      ;;
esac
exit 0
